name: Deploy To Staging Server
on:
  push:
    branches:
      - staging
jobs:
  deploy:
    runs-on: [self-hosted, pull-to-server-staging]
    steps:
      - name: Run git commands
        run: |
          cd /workdir/
          git checkout main
          git pull origin main
          git checkout staging
          git reset --hard main
          git pull origin staging
          echo "Staging server updated from remote"